### ISSUE TITLE
Unable to view kube dashboard in Kind

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#281]
- Dashboard and service account is created fine
- When viewing the dashboard there's a long loading indicator followed by a blank screen
```
Request: [2020-01-22T15:38:20Z] Remote-IP:"127.0.0.1" Method:"GET" Path:"/pp/v1/apps/kubedash/ui/el1Yy6G5BlhiiP3eyzf39UlZX7U/styles.bb1efa96a359b8cd45d9.css" Status:200 Latency:11.281147ms Bytes-In:0 Bytes-Out:0
{"time":"2020-01-22T15:38:20.618953552Z","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] net/http: abort Handler goroutine 3718 [running]:\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x1f27200, 0x1000, 0xc000980000, 0x22a5f60, 0xc000312000)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/recover.go:71 +0xf1\npanic(0x1bccf80, 0xc0000cea20)\n\t/home/richard/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5\nnet/http/httputil.(*ReverseProxy).ServeHTTP(0xc000267860, 0x2241880, 0xc000a2a540, 0xc000c9eca0)\n\t/home/richard/.gimme/versions/go1.12.linux.amd64/src/net/http/httputil/reverseproxy.go:309 +0x1621\ngithub.com/cloudfoundry-incubator/stratos/src/jetstream/plugins/kubernetes/dashboard.KubeDashboardProxy(0x22a5f60, 0xc000312000, 0x22a5be0, 0xc000260500, 0xc0003a8f00, 0x0, 0x24)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/plugins/kubernetes/dashboard/proxy.go:134 +0xe8c\ngithub.com/cloudfoundry-incubator/stratos/src/jetstream/plugins/kubernetes.(*KubernetesSpecification).kubeDashboardProxy(0xc000a34260, 0x22a5f60, 0xc000312000, 0xc0009d3f20, 0x1e66f03)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/plugins/kubernetes/kube_dashboard.go:49 +0x3a6\nmain.(*portalProxy).xsrfMiddleware.func1(0x22a5f60, 0xc000312000, 0x7, 0x1b55860)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:104 +0x108\nmain.(*portalProxy).sessionMiddleware.func1(0x22a5f60, 0xc000312000, 0x1e53740, 0x6)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:71 +0x617\nmain.(*portalProxy).setSecureCacheContentMiddleware.func1(0x22a5f60, 0xc000312000, 0x1, 0x8)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:181 +0x235\ngithub.com/labstack/echo.(*Echo).Add.func1(0x22a5f60, 0xc000312000, 0x1e50660, 0x3)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:490 +0x87\nmain.(*portalProxy).urlCheckMiddleware.func1(0x22a5f60, 0xc000312000, 0x1e53740, 0x6)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:165 +0x15c\nmain.(*portalProxy).setStaticCacheContentMiddleware.func1(0x22a5f60, 0xc000312000, 0xc000a1a420, 0x10)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:173 +0x235\nmain.retryAfterUpgradeMiddleware.func1(0x22a5f60, 0xc000312000, 0xc00098b818, 0x1)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:236 +0x39\nmain.errorLoggingMiddleware.func1(0x22a5f60, 0xc000312000, 0x1e627e3, 0xf)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:210 +0xb1\ngithub.com/labstack/echo/middleware.SecureWithConfig.func1.1(0x22a5f60, 0xc000312000, 0x1e85021, 0x20)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/secure.go:113 +0x15b\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1(0x22a5f60, 0xc000312000, 0x1f27200, 0x1000)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/cors.go:117 +0x40b\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0x22a5f60, 0xc000312000, 0x0, 0x0)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/recover.go:78 +0xd5\ngithub.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0x22a5f60, 0xc000312000, 0xc00098bc68, 0x1)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/logger.go:118 +0x1c0\nmain.sessionCleanupMiddleware.func1(0x22a5f60, 0xc000312000, 0x3, 0xc0009ca1c4)\n\t/home/richard/dev/github/stratos-ui-suse-2/src/jetstream/middleware.go:144 +0x9d\ngithub.com/labstack/echo.(*Echo).ServeHTTP(0xc000a28000, 0x2241880, 0xc000a2a540, 0xc00016b300)\n\t/home/richard/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:593 +0x221\nnet/http.serverHandler.ServeHTTP(0xc000a1e5b0, 0x2241880, 0xc000a2a540, 0xc00016b300)\n\t/home/richard/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:2774 +0xab\nnet/http.(*conn).serve(0xc00073a280, 0x2249500, 0xc00087ab00)\n\t/home/richard/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:1878 +0x84c\ncreated by net/http.(*Server).Serve\n\t/home/richard/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:2884\n"}
echo: http: superfluous response.WriteHeader call from github.com/labstack/echo.(*Response).WriteHeader (response.go:63)
{"time":"2020-01-22T15:38:20.619156501Z","level":"ERROR","prefix":"echo","file":"main.go","line":"991","message":"net/http: abort Handler"}
Request: [2020-01-22T15:38:20Z] Remote-IP:"127.0.0.1" Method:"GET" Path:"/pp/v1/apps/kubedash/ui/el1Yy6G5BlhiiP3eyzf39UlZX7U/polyfills.40201eb41e540c91bd50.js" Status:500 Latency:19.626128ms Bytes-In:0 Bytes-Out:21
```

**Comment by richard-cox** [comment]
Closing. Tested on a branch (3.2.0 with entity access changes) and this worked fine using Kind 0.8.0 (Kube v1.18.2)
